apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hello-world-ia
  template:
    metadata:
      labels:
        app: hello-world-ia
    spec:
       containers:
       - name: hello-world
         image: aryeldevops/hello-world-ia:v2
         ports:
         - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  selector:
    app: hello-world-ia
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
  type: LoadBalancer